# NumPy Exercises
import numpy 

In [159]:
import numpy as np

Q1. Extract all odd numbers from arr

Input:

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Desired output:

array([1, 3, 5, 7, 9])

In [130]:
arr=np.arange(0,10,1)
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

Q.2. Replace all odd numbers in arr with -1

Desired Output:

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [50]:
arr=np.arange(0,10)
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [49]:
arr1=arr.copy()
arr1[arr1%2!=0]=-1
arr1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Q.3. Convert a 1D array to a 2D array with 2 rows


**Input :**

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Desired Output:**

array([[0, 1, 2, 3, 4],

       [5, 6, 7, 8, 9]])

In [52]:
arr=np.arange(0,10,1)
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

How to stack two arrays vertically?
Q. Stack arrays a and b vertically
Input

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
Desired Output:

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [88]:
a = np.arange(10).reshape(2,5)
b = np.repeat(1,5).reshape(1,5)
#np.concatenate([a,b])
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1]])

In [63]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Q.4. Create the following pattern without hardcoding. Use only numpy functions and the below input array a.

**Input:**

a = np.array([1,2,3])

**Desired Output:**

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [72]:
a=np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

Q.5.  Get the common items between a and b

**Input:**

a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

**Desired Output:**

array([2, 4])

In [73]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

Q.6. From array a remove all items present in array b

**Input:**

a = np.array([1,2,3,4,5])

b = np.array([5,6,7,8,9])

**Desired Output:**

array([1,2,3,4])

In [91]:
a = np.array([1,2,3,4,5,6])

b = np.array([5,6,4,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3])

In [96]:
#Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,6])
np.where(a==b)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [102]:
#. Get all items between 5 and 10 from a
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>=5) & (a<=11)]

array([ 6,  9, 10])

In [105]:
#Swap rows 1 and 2 in the array arr
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [112]:
arr[[1,0,2]]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

In [113]:
# Reverse the columns of a 2D array arr.
# Input
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [116]:
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Q.7.  Compute the one-hot encodings (dummy binary variables for each unique value in the array)

Input:

np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
### array([2, 3, 2, 2, 2, 1])
Output:

### array([[ 0.,  1.,  0.],
###                  [ 0.,  0.,  1.],
###        [ 0.,  1.,  0.],
###        [ 0.,  1.,  0.],
###        [ 0.,  1.,  0.],
###        [ 1.,  0.,  0.]])

In [147]:
np.random.seed(101)
arr = np.random.randint(1,4, size=6) 
arr

array([2, 3, 2, 2, 2, 1])

In [148]:
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out

one_hot_encodings(arr)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [145]:
list(enumerate([1, 2,4]))

[(0, 1), (1, 2), (2, 4)]

In [146]:
a=np.unique(arr)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Q.8.  Create a numpy array of length 10, starting from 5 and has a step of 3 between consecutive numbers.

Desired Output
### array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [156]:
def seq(s,l,st):
    end=s+(st*l)
    return np.arange(s,end,st)

In [158]:
seq(5,10,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [173]:
#remove nan 
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
a[~np.isnan(a)]

array([1., 2., 3., 5., 6., 7.])

In [4]:
parrot='Norwegian Blue'
print(parrot[3])
print(parrot[4])
print(parrot[-5])
print(parrot[3])
print(parrot[6])
print(parrot[-6])


w
e
 
w
i
n


In [5]:
letters='abcdefghijklmnopqrstuvwxyz'

In [17]:
letters[16:13:-1]

'qpo'

In [23]:
letters[4::-1]

'edcba'

In [30]:
letters[:-9:-1]

'zyxwvuts'

In [35]:
letters[1::-1]

'ba'

In [36]:

meal1 = "spam" + "eggs" + "beans"
meal2 = "spam\neggs\nbeans"
meal3 = "spam, eggs, beans"
meal4 = """spam
eggs
beans"""

In [40]:
print(meal4)

spam
eggs
beans


In [41]:
days = "Mon, Tue, Wed, Thu, Fri, Sat, Sun"
print(days[::5])

MTWTFSS


In [42]:
data = "1:A, 2:B, 3:C, 4:D, 5:E, 6:F, 7:G, 8:H"

In [45]:
data[0:-1:5]

'12345678'